apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
  name: web
  namespace: web-1
spec:
  containers:
  - image: nginx:1.21.4
    name: meu-container-web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

